### Login admin
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "administrator",
    "password" : "123456"
}

### Login user
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "user02",
    "password" : "123456"
}

### Logout
POST localhost:3000/api/auth/logout
Accept: application/json


### Register
POST localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "username": "user02",
    "password" : "123456"
}




