### GET user profile list
GET http://localhost:3000/api/user_profiles
Accept: application/json

### GET user profile by ID
GET http://localhost:3000/api/user_profiles/35

### GET user profile by token
GET http://localhost:3000/api/user_profiles/details
