### Get All User
GET http://localhost:3000/api/users
Accept: application/json
###

### Create a new user
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
    "username": "triani12",
    "password": "akudaktau123",
    "role": "user"
}
###

### Get User By ID
GET http://localhost:3000/api/users/15
Accept: application/json
###


### Update user by ID
PUT http://localhost:3000/api/users/15
Accept: application/json
Content-Type: application/json

{
    "username": "ilyasand",
    "role": "user"
}
###

### Delete a User By ID
DELETE http://localhost:3000/api/users/12
Accept: application/json
###


### Login
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "triani12",
    "password" : "akudaktau123"
}
###

### Logout
POST localhost:3000/api/auth/logout
Accept: application/json
###
