### Get All User
GET http://localhost:3000/api/users
Accept: application/json
###



### Get User By ID
GET http://localhost:3000/api/users/15
Accept: application/json
###


### Update user by ID
PUT http://localhost:3000/api/users/15
Accept: application/json
Content-Type: application/json

{
    "username": "ilyasand",
    "role": "user"
}
###

### Delete a User By ID
DELETE http://localhost:3000/api/users/20
Accept: application/json
###


### Login user
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "triani12",
    "password" : "akudaktau123"
}
###

### Login admin
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "administrator",
    "password" : "akudaktau123"
}
###

### Logout
POST localhost:3000/api/auth/logout
Accept: application/json
###

### Register
POST http://localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{
    "username": "adam123",
    "password": "akudaktau123",
    "role": "admin"
}
###

